# main text of home
name: Emre Sokullu
bio: Founder & CEO Grou.ps Inc.

# twitter summary info
description: A blog about technology and stuff related

picture: assets/images/picture.jpg

url: http://www.emresokullu.com
# your url: http://USERNAME.github.io

# if you don't have any of social below, comment the line
facebook: esokullu
twitter: emresokullu
github: esokullu
email: emre@groups-inc.com

gems:
  - jekyll-seo-tag

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, travis.sh, vendor]
